### ISSUE TITLE
Write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by PiyushB001** [arduino/summer-of-code#11]
Greetings, 
I would like to introduce myself as Piyush Bhatia, a sophomore engineering undergrad in the field of Electronics and Communication Technology IIIT-Una, India.

The project I am interested in for the year 2020 iteration of GSoC is "Write MicroPython examples and tools for Portenta". I have previously worked on Arduino Uno and Mega for a couple of my personal projects. I have prior experience in Machine Learning and Deep Learning and have undertaken industrial Training and a couple of courses regarding the same. 

I had a glance at that Arduino's Github profile and tried searching for something related to Portenta but failed at this given task. I would be really kind of you if you can pinpoint me from where to start from and what is actually expected in terms of example domains from this project.

Thanks in advance.

**Comment by dushyant18033** [comment]
Hi,
I am Dushyant Panchal, a second year B.Tech Computer Science and Engineering student from Indraprastha Institute of Information Technology, Delhi and I am looking forward to contribute to the betterment of Arduino and Portenta community.

The project I'm very much interested in and would like to give my best contribution to for GSOC 2020 is "**Writing MicroPython examples and tools for Portenta**".

**I have more than 3 years of experience working with Arduino UNO and have worked on many interactive projects** including an Arduino-based firmware for quadcopter flight control (still under development), a self balancing bot, a helpcap (a cap-like device that can emulate mouse events on specific head movements connected to the PC via bluetooth) which was also selected among the top projects in my college course project showcase. I have also worked a little bit with nodeMCU (both via MicroPython and Arduino IDE). Hence **I assure that this is going to be more of a passion for me than work.**

I just learnt about this Arduino Portenta H7 to be released in March 2020 and wish to have a hands-on experience with this powerful board. 

**Doubt 1:** How can I contact a GSOC mentor for your organisation? Should I directly mail to: summer-of-code@arduino.cc for any queries and doubts? Is there a slack channel that I can connect to?

**Doubt 2:** Since the board we're going to work for has not been released yet, I wanted to ask whether the standard libraries and code uploading protocols would be similar to other arduino boards or very much different? Or will it be similar to MicroPython for NodeMCU?
Like **is there a dedicated Portenta github repository** or project that I could start looking at?

Looking forward towards a positive response.

Thanks and Regards
dushyant18033@iiitd.ac.in

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini


These are some example of micropython I want to work with you to make tools for portenta.
Looking forward to becoming part of the Arduino Community and making contributions

**Comment by thekunalsaini** [comment]
[Arduino.txt](https://github.com/arduino/summer-of-code/files/4244273/Arduino.txt)
[Arduino2.txt](https://github.com/arduino/summer-of-code/files/4244274/Arduino2.txt)

Some examples of Micropython

**Comment by tkhabia** [comment]
Hi, 
I  am the Tanmay khabia from  IIIT Hyderabad, India. I am a second-year undergraduate student ece branch. I have been working with Arduino for many of my IoT Project using Arduino UNO and NodeMCU.
I am interested in  this year GSoC 2020 project Write MicroPython examples and tools for Portenta, Can I get some suggestion about how to get started and contribute?
Thank you

**Comment by Chester-King** [comment]
Greetings,
I am Madhur Dixit, a third year student pursuing Btech in Computer Science and Engineering from Vellore Institute of Technology, Vellore, India.
I am looking forward to making valuable contributions to the Arduino and Portenta repositories.
       I have worked extensively with various microcontrollers including arduino UNO, MEGA, Node MCU and raspberry pi. I am actively involved in working with IoT, Cloud and android. I have also developed various applications which involve connection of the microcontrollers to the cloud for sending and receiving information from the cloud.The project I am interested in for the year 2020 iteration of GSoC is "Write MicroPython examples and tools for Portenta".
I support my endeavor to work on this project because I am well-versed with python on raspberry pi and C++ on arduino. I looked up examples of MicroPython scripts on the internet to perceive what exactly I was getting into. Upon seeing the data available on it, I was assured that I would be able to work on this project concerning writing examples about using MicroPython on a Portenta board and achieve optimal results.

Thanks & Regards

**Comment by alranel** [comment]
Hi all! I'm going to give some information about this project.
The selected students with a project related to the Portenta board will be provided a Portenta board for free, along with access to the software we're writing for it.
The data sheet of the board can be found here: https://store.arduino.cc/usa/portenta-h7

Any example showing how to use MicroPython on the Portenta board is welcome, so use your creativity and propose cool examples :) For starters, you could show how to use all the hardware peripherals from Python. Or you might port many existing Arduino examples to MicroPython.

@dushyant18033 for any question just write here (I suggest to open your own issue so that we can use it as an individual communication channel). To answer your questions:
* The Portenta board can be programmed with the existing Arduino toolchain if you want to upload Arduino (C++) sketches. But if you want to use MicroPython code, the upload is much more like NodeMCU. 
* As of now there's no public GitHub repository as we are actively writing code, but we will release it before the GSoC activity starts.

Hints:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)
