### ISSUE TITLE
Write JerryScript (JavaScript) examples and tools for Portenta

### ISSUE THREAD

**Issue by salisbuk7897** [arduino/summer-of-code#2]
Hi, My name is Salisu Ali. I'm an undergraduate student and a self taught developer for 3 years. I work with arduino Uno R3, ESP8266 WIFI module, etc where I build home automation system as well as temperature and heart rate tracking system. I have some experience with machine learning models too. My programming languages are python, java, c++, C#,JavaScript and a little of COBOL and Rexx.
    I have no experience with Open Source Contribution. But hopefully I will soon catch up with the process. I'm intrested in the project "Write JerryScript (JavaScript) examples and tools for Portenta."
Evidence of my work can be found on my twitter handle @salisuA86505578. Thank you!

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini

Doubt:- Can we add an advance level example or basic one ?

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by utkarshg99** [comment]
Hello all,

My name is Utkarsh Gupta and I am a Sophomore, Electrical Engineering at Indian Institute of Technology, Kanpur. I have been working with Arduino for over 2 years now and have implemented various IoT as well as Communication System Projects on Arduino. I have a firm grasp on Javascript as I am a full-stack developer (Frontend frameworks like Vue, Backend: NodeJS). I am greatly interested in contributing to Arduino by participating in GSoC'20.
It would be great if someone from the community can provide a few topics on which I can provide examples. Also, where do we have to submit our code?

Thanks for your time, looking forward to contributing to the awesome community.

**Comment by salisbuk7897** [comment]
Hi,
   Great experience you have there. Meanwhile, as we wait for the Arduino team to reply and Guide us towards submitting a proposal. I wish us all the best of luck.

regards,
Salisu Ali

**Comment by alranel** [comment]
Hello! Here are some hints for you:

* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

I'm closing this issue because too many students wrote :) Let's have separate issues as individual communication channels.
