### ISSUE TITLE
Idea: write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by sushantag9** [arduino/summer-of-code#26]
Hi, I am intrested in workin gon this project. I have an experience of worrking with Arduino, Raspberry Pie, jetson Nano and Movidius Stick.
With this in my skill set I would like to contribute by best to the community. Arduino + python is like iceing on the cake

**Comment by alranel** [comment]
Welcome!

Some hints for you:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)
