### ISSUE TITLE
Write Examples for Arduino Libraries 

### ISSUE THREAD

**Issue by MahmoudOsama97** [arduino/summer-of-code#28]

**Comment by MahmoudOsama97** [comment]
i am Mahmoud Osama Mahmoud Soliman from Cairo Egypt ,3rd year computer and system engineer ainshms university.
i find that writing examples for arduino libraries is pretty interesting ,as it will help a lot of people around the world to use it ,as when i started using arduino some times i found difficulty in using some libraries , now as i became good in embedded systems using AVR and TIVAC , by taking some diplomas and courses and also got a software engineering course so i am pretty good in documenting , testing and using git .
so i have very good ideas as i love coding and testing by using hardware .

**Comment by alranel** [comment]
Welcome!

Some hints for you:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)
