### ISSUE TITLE
Write MicroPython examples and tools for Portenta

### ISSUE THREAD

**Issue by Captain-Stack** [arduino/summer-of-code#5]
Hi I am an Undergraduate student and have some working experience with arduino nano.,uno,mega and nodemcu.I have also some experience working with micropython.I also have experience working with Python ,c ,and c++ language.Can you please help me by pointing out which kind of code can be added to the project?

**Comment by 96vksingh** [comment]
Hi, I am @96vksingh and an undergraduate student. I have experience in c,c++and python. It seems interesting Arduino with python. Can you please suggest me some examples on which to focus on and sensors to be used? Further you can see my workings on my GitHub profile(@96vksingh).

**Comment by bhatakti-atama** [comment]
Hi I would like to know more about this issue. I don't have a portenta board available is there any recommended simulator?

**Comment by hnumair** [comment]
Greetings,
I am an undergraduate student as well and have fair knowledge of C and Python. To be completely honest I haven't worked on any industrial level project but would like to contribute to this project. Can I get some contact details of the mentor(s) so I can ask few more relevant things?

**Comment by manan2501** [comment]
Hi, I am an undergraduate student, studying Electronics and Communication Engineering in Surat, India. I had previously worked with arduino Nano, Uno, and nodemcu. I am interested in AI and Cybersecurity, this would help me to use Portenta uniquely and write great examples. I had working with Python ,c, and c++ language in the past. I cannot wait to get my hands dirty, Please point me to the starting point?

**Comment by JahnaviChitta** [comment]
Hi I am Jahnavi, an undergraduate student. I had experience working on arduino nano, UNO, nodemcu as well as raspberrpi. I have also written some programs on my own to make use of them in my projects. I have very good grip on python, c, c++ too. So, I would be a great pleasure if you point me to the starting point, so that I can use my knowledge in a productive way. You can see my workings on my github profile (@JahnaviChitta) .

**Comment by thekunalsaini** [comment]
Hello all,
I am Kunal Saini from Kurukshetra, Haryana, India. I am a 3rd-year undergraduate student. I have worked on Arduino from very beginning i.e. from LED blinking to automation using IoT with IBM watson and building a mobile and robots using Arduino.
I have made lots of example .
Thank you,
Kunal Saini

Familiar with tool development

Looking forward to becoming part of the Arduino Community and making contributions

**Comment by thekunalsaini** [comment]
@Captain-Stack  here is one example 
[Arduino.txt](https://github.com/arduino/summer-of-code/files/4244284/Arduino.txt)

**Comment by alranel** [comment]
@Captain-Stack what task are you interested in?

Hints:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

**Comment by alranel** [comment]
@Captain-Stack any example about using MicroPython with the Portenta board is welcome :)
For instance, you might want to cover all the hardware peripherals of the board. Or you might want to port the many existing Arduino examples.

Hints for everybody:
* make sure you read the [ideas list](https://github.com/arduino/summer-of-code/blob/master/ideas.md) (we recently added more ideas and more details)
* in order to write your proposal, follow the [guide](https://github.com/arduino/summer-of-code/blob/master/how-to-apply.md)
* for any question, use this issue tracker and we will answer (but note: only one issue per student! write all your questions inside one issue)

**Comment by Captain-Stack** [comment]
@alranel  thank you for your previous reply. In the application guide it is suggested to review the proposal by the mentor before submitting the final one.Can you please tell me how I can send my proposal for review ?
