### ISSUE TITLE
Gsoc2020:-Analyzer for Arduino libraries

### ISSUE THREAD

**Issue by BeAsTmAsTeR169** [arduino/summer-of-code#75]

**Comment by alranel** [comment]
Hello @BeAsTmAsTeR169, and welcome.
The term crawler is used in this context because the libraries are distributed in hundreds of repositories, so such analyzer will need to scan all of them in order to gather the required information, clone their content and analyze it.
There's no requirement in terms of C++ analyzers to be used, so you can propose a solution.
