### ISSUE TITLE
Self introduction and questions about the idea: "Write JerryScript (JavaScript) examples and tools for Portenta"

### ISSUE THREAD

**Issue by dragonman225** [arduino/summer-of-code#95]
Hello, I'm Wang Wen-Zhi (Alexander), currently studying EE at [National Chiao Tung University](https://www.nctu.edu.tw/en) in Taiwan.

I'm a JavaScript developer and I have created several Node.js projects. For now, [Notablog](https://github.com/dragonman225/notablog), [notionapi-agent](https://github.com/dragonman225/notionapi-agent), [NAST](https://github.com/dragonman225/nast) are some more mature ones.

I also program in C for embedded systems, for instance, [stm32f469-usbaudio](https://github.com/dragonman225/stm32f469-usbaudio) is a working USB soundcard firmware, which supports UAC 1.0 asynchronous mode, for STM32469I-Discovery development board.

By the way, I had experience in writing ARM Cortex-M assembly code while I was taking this [Microprocessor System Lab.](https://ocw.nctu.edu.tw/eng/course_detail-v.php?bgid=9&gid=0&nid=572) course.

I would like to work on the idea: "Write JerryScript (JavaScript) examples and tools for Portenta", but I have two questions:

1. How are we going to work with JerryScript in practice?

   I quickly browsed the [documentation](https://github.com/jerryscript-project/jerryscript/tree/master/docs) of JerryScript, and I didn't find any APIs related to hardware, so I think it may be a pure JavaScript engine. In this way, how are we going to work with JS in practice? Will there be a set of JS APIs for accessing peripherals defined by the Arduino team and we can use them to write examples? Or are we going to design the APIs, implement them in C or C++, create JS bindings, and finally write examples?

2. How will Portenta run JerryScript engine?

   I notice that there are various [supported targets](https://github.com/jerryscript-project/jerryscript/tree/master/targets) in JerryScript's repo, and they are using different RTOS. So, what will Portenta use? Maybe FreeRTOS as listed in the ideas list? But what should we do when FreeRTOS porting is not completed yet?

It's exciting to explore what could be achieved with this small yet powerful board!

Best wishes,

Alexander

**Comment by AbhinavMir** [comment]
For your second question, I assume it's running on top of mBed.
Disclaimer: Not from Arduino! 
All the best Alexander!
Abhinav

**Comment by alranel** [comment]
Hello @dragonman225 and welcome! Also, thank you for introducing yourself and providing references to your past experience.

Your questions are good questions. I'll try to answer.
As you wrote, FreeRTOS is not ported yet so that is not an option for now. But we are going to release the mbed stack for Portenta, and JerryScript can run on top of it. See this documentation: https://os.mbed.com/javascript-on-mbed/

Regarding the hardware APIs, writing the bindings should be part of your proposal. We have in roadmap to work on this, but we haven't started yet so it could be a real-time collaboration between you and us during your summer of code.
